### PR TITLE
Resolve all outstanding mypy issues - mostly np.array -> np.ndarray.

### PR DESCRIPTION
**Pull request by coledie**
These were preventing me from using pre-commit install.

### CODE REVIEW

**Comment by mortid0** [comment]
Could you update `mypy.ini` to show which issues are resolved? It seems it is empty, do we need to update mypy?

**Comment by coledie** [comment]
No update needed to mypy.ini.

**Comment by mortid0** [comment]
> No update needed to mypy.ini.

Then how these issues can be triggered and why we don't see them in CI pipeline?

**Comment by coledie** [comment]
I use "pre-commit run --all-files" a lot which is where I get these.

**Comment by mortid0** [comment]
> I use "pre-commit run --all-files" a lot which is where I get these.

Probably CI is using [an old version of mypy](https://github.com/microsoft/DeepGNN/blob/main/.github/actions/lint/action.yml#L15) in comparison your local, could you update in this PR, so we'll catch these issues later?

**Pull request merged**
